import Head from 'next/head'
import Link from 'next/link'
import cardStyles from '../styles/Card.module.css'
import { request } from '../request';
import Gif from '../src/components/index/Gif'
import Carousel from '../src/components/layout/Carousel'

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>video </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel />
      <main>
        <div className="container">
          <ul>
            <li>1</li>
            <li>3</li>
            <li>4</li>
            <li>ad</li>
          </ul>
          {/* <ul className={cardStyles.cardGroup}>
            {data.map((video) =>(
              <li key={video.id} className={cardStyles.card}>
                <Gif 
                anime={video.imgInfo.images.downsized.url} 
                fixed={video.imgInfo.images.original_still.url}
                info={{title:video.imgInfo.title,width:video.imgInfo.images.width,heigth:video.imgInfo.images.height }} 
                /> 
                <div className={cardStyles.cardContent}>
                  <h2>{video.title}</h2>
                  <p>{video.author}</p>
                  <p>{video.publishTime}</p>
                  <Link href={`./video/${video.id}`}>
                    前往
                  </Link>
                </div>
              </li>
            ))}
          </ul> */}
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await request.get(`/api/video`)
  const data = await res.data

  // async function getImgData (element) {
  //   const imgRes = await request.get(`v1/gifs/search?api_key=ov5oCUoBAwq1LDVTLwNPz1KVQPqxLYTp&q=${element.search}&limit=1`,{
  //     baseURL: 'https://api.giphy.com' 
  //   })
  //   const imgInfo = await imgRes.data.data
  //   element.imgInfo = imgInfo[0]  
  // }

  // for(const element of data) {
  //   await getImgData(element)
  // }

  // Pass data to the page via props
  return { props: { data } }
}
